package com.ailu.pycontext.dao.mapper;

import com.ailu.pycontext.dao.bean.allMsg;
import com.ailu.pycontext.dao.bean.allMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface allMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    long countByExample(allMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int deleteByExample(allMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int insert(allMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int insertSelective(allMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    List<allMsg> selectByExample(allMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    allMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") allMsg record, @Param("example") allMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") allMsg record, @Param("example") allMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(allMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(allMsg record);
}