package com.ailu.pycontext.dao.mapper;

import com.ailu.pycontext.dao.bean.AllMsg;
import com.ailu.pycontext.dao.bean.AllMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    long countByExample(AllMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int deleteByExample(AllMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int insert(AllMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int insertSelective(AllMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    List<AllMsg> selectByExample(AllMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    AllMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllMsg record, @Param("example") AllMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllMsg record, @Param("example") AllMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllMsg record);
}