package com.ailu.pycontext.dao.bean;

import java.util.Date;

public class allMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_msg.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_msg.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_msg.duration
     *
     * @mbg.generated
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_msg.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_msg.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_msg.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_msg.id
     *
     * @return the value of all_msg.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_msg.id
     *
     * @param id the value for all_msg.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_msg.content
     *
     * @return the value of all_msg.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_msg.content
     *
     * @param content the value for all_msg.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_msg.duration
     *
     * @return the value of all_msg.duration
     *
     * @mbg.generated
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_msg.duration
     *
     * @param duration the value for all_msg.duration
     *
     * @mbg.generated
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_msg.type
     *
     * @return the value of all_msg.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_msg.type
     *
     * @param type the value for all_msg.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_msg.ctime
     *
     * @return the value of all_msg.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_msg.ctime
     *
     * @param ctime the value for all_msg.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_msg.utime
     *
     * @return the value of all_msg.utime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_msg.utime
     *
     * @param utime the value for all_msg.utime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}